### ISSUE TITLE
linkの出力パスと画像出力ディレクトリのパスを別で指定したい

### ISSUE THREAD

**Issue by nenrinyear** [rokuosan/github-issue-cms#14]
## Feature overview
- 出力されるaタグのリンクと出力先フォルダの指定を別で行いたい

## Reason
- Next.jsでは`/public`配下にstaticなファイルを置く必要がある
- ただ、URLは`/public`が`/`としてルーティングされる
- そのため、出力されるaタグのリンクと出力先フォルダの指定を別で行いたい

**Comment by rokuosan** [comment]
#16 で対応済みなのでCloseします
