### ISSUE TITLE
请看一下

### ISSUE THREAD

**Issue by g0fcn** [rokuosan/github-issue-cms#4]
https://github.com/g0fcn/g0fcn.github.io/actions/runs/7987445701/job/21809945149#step:5:1

**Comment by rokuosan** [comment]
Please change the following part of the Workflow to resemble the second code block:

```yaml
    - name: Generate
      run: github-issue-cms --token=${{ secrets.GH_TOKEN }}
```

```yaml
    - name: Generate
      run: github-issue-cms generate --token=${{ secrets.GH_TOKEN }}
```

I forgot to mention the modification of the command in the README. I apologize for the oversight. Please try with this content.

Thanks for your report.
