### ISSUE TITLE
大佬看下

### ISSUE THREAD

**Issue by g0fcn** [rokuosan/github-issue-cms#5]
https://github.com/g0fcn/g0fcn.github.io/actions/runs/8013316309/job/21890155891#step:5:1

**Comment by g0fcn** [comment]
这要自己拉过来自己改吧应该

**Comment by g0fcn** [comment]
https://github.com/xyming108/sulv-hugo-papermod
用这个主题试了下也还是不行啊

**Comment by rokuosan** [comment]
I fixed the issue. Please use ``v0.2.4``.

If you have solved the problem I would appreciate your comments.

**Comment by g0fcn** [comment]
可以了，不过应该还缺一个文章入库的选项，默认只在posts

**Comment by g0fcn** [comment]
感谢大佬

**Comment by g0fcn** [comment]
或者posts/随意什么文件，不然太乱了

**Comment by rokuosan** [comment]
> 可以了，不过应该还缺一个文章入库的选项，默认只在posts

I can't understand what you mean. 
Do you mean you want to connect to any RDBMS?

If so, that's not possible. This application only provides a mechanism to save issues on the specified repository as Markdown. This makes it easier to integrate into existing projects.

Or do you mean you want to specify the output directory? That feature has not been implemented yet. If you can implement it in Go language, please submit a Pull Request. Alternatively, you can open a new feature request as an issue.

I am Japanese. So I can't understand Chinese. If you want to convey your message accurately, please write it in English or Japanese.

**Comment by g0fcn** [comment]
提取md文件到posts/任何地方，只是在posts很乱

**Comment by rokuosan** [comment]
> > 可以了，不过应该还缺一个文章入库的选项，默认只在posts
> 
> I can't understand what you mean. Do you mean you want to connect to any RDBMS?
> 
> If so, that's not possible. This application only provides a mechanism to save issues on the specified repository as Markdown. This makes it easier to integrate into existing projects.
> 
> Or do you mean you want to specify the output directory? That feature has not been implemented yet. If you can implement it in Go language, please submit a Pull Request. Alternatively, you can open a new feature request as an issue.
> 
> I am Japanese. So I can't understand Chinese. If you want to convey your message accurately, please write it in English or Japanese.

あなたが言いたいのはこれに該当しないということでしょうか。
意図が理解できません。**あなたの言いたいこと、実現したいことを明確かつ簡潔に説明してください**。

Markdownの出力される場所が``content/posts``直下であり、``0000000.md``のようなファイルが増えることについて指摘しているのでしょうか。
ご指摘の通り、記事が増えるにつれMarkdownファイルが増えていきますが、このアプリケーションでは記事のすべてをGitHub上のIssueから管理できるようになっているため、実際のファイルを参照する必要はないはずです。

また、Hugoのデフォルトでは記事があるディレクトリをそのままURL (Slug）として利用しますが、Frontmatterを使うことで任意のURL(Slug)を指定することができます。
もしディレクトリとURLの関係で困っているならば、この機能を利用することで解決できます。

HugoのFrontmatterの詳細については以下のページを参照してください。
https://gohugo.io/content-management/front-matter/

**Comment by g0fcn** [comment]
![IMG_20240223_195443.jpg](https://github.com/rokuosan/github-issue-cms/assets/156695055/c57ff28c-066e-4c2a-847a-3f90df93c7b2)

**Comment by g0fcn** [comment]
この2つのニーズは少し似ています

**Comment by g0fcn** [comment]
![IMG_20240223_200425.jpg](https://github.com/rokuosan/github-issue-cms/assets/156695055/d9484e21-be9d-422e-9e8f-baf600075ddd)

**Comment by rokuosan** [comment]
投稿された画像から推察すると、``content/posts/``以降の出力先を変えたいということでしょうか。

現在そのような機能は実装していませんが、2つの機能について検討しています。

1. **Issueすべての出力先を変更するオプション**
これは出力先を任意のディレクトリに変更する機能です。
例えば``content/posts/daily``を指定した場合は、Issueすべてがそのディレクトリに出力されます。

2. **個別の出力先を指定する機能**
Issueの内容によって出力先を分ける機能については、手法や考慮すべき点がいくつかあります。
例えばカテゴリ別に分ける方法や、特別なメタデータを利用する方法です。
この機能については、もう少し後の実装になるでしょう。

**Comment by g0fcn** [comment]
Okay, I look forward to it

**Comment by rokuosan** [comment]
> 投稿された画像から推察すると、`content/posts/`以降の出力先を変えたいということでしょうか。
> 
> 現在そのような機能は実装していませんが、2つの機能について検討しています。
> 
> 1. **Issueすべての出力先を変更するオプション**
>    これは出力先を任意のディレクトリに変更する機能です。
>    例えば`content/posts/daily`を指定した場合は、Issueすべてがそのディレクトリに出力されます。
> 2. **個別の出力先を指定する機能**
>    Issueの内容によって出力先を分ける機能については、手法や考慮すべき点がいくつかあります。
>    例えばカテゴリ別に分ける方法や、特別なメタデータを利用する方法です。
>    この機能については、もう少し後の実装になるでしょう。

I  have implemented the features indicated in 1. Please try ``v0.3.0``.

Edit gic.config.yaml as follows:
```yaml
github:
  username: 'YOUR_NAME'
  repository: 'YOUR_REPOSITORY'

hugo:
  directory:
    articles: 'content/posts'
  url:
    images: '/images'
```

**Comment by g0fcn** [comment]
666
